[package]
name = "cdp-policy"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
inotify = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = "3"
