[package]
name = "cdp-browser"
version.workspace = true
edition.workspace = true

[dependencies]
cdp-crypto = { workspace = true }
tokio = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }
libc = { workspace = true }
regex = "1"
