[package]
name = "cdp-proxy"
version.workspace = true
edition.workspace = true

[dependencies]
cdp-crypto = { workspace = true }
cdp-policy = { workspace = true }
cdp-lease = { workspace = true }
cdp-audit = { workspace = true }
tokio = { workspace = true }
hyper = { version = "1", features = ["server", "client", "http1"] }
hyper-util = { version = "0.1", features = ["tokio", "server-auto", "client-legacy"] }
http-body-util = "0.1"
http = "1"
bytes = "1"
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zeroize = { workspace = true }
nix = { workspace = true }
globset = "0.4"
chrono = { workspace = true }
libc = { workspace = true }
rcgen = "0.13"
rustls = { version = "0.23", features = ["ring"] }
tokio-rustls = "0.26"
webpki-roots = "0.26"
time = "0.3"
cdp-browser = { workspace = true }

[features]
test-support = []

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
