[package]
name = "cdp-vault"
version.workspace = true
edition.workspace = true

[dependencies]
cdp-crypto = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
nix = { workspace = true }
libc = { workspace = true }
chacha20poly1305 = { workspace = true }
argon2 = { workspace = true }
zeroize = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
seccompiler = { workspace = true }

[dev-dependencies]
tempfile = "3"
